version: '3'
services:
  db:
    image: postgres:10.5
    command: postgres -c 'max_connections=1000' -c 'shared_buffers=256MB'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    links:
      - db
    volumes:
      - .:/app
    command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
